export interface GodvilleHero {
	name: string;
	godname: string;
	gender: string;
	g_gender: string;
	gold_approx: string;
	level: number;
	quest: string;
	quest_progress: number;
	exp_progress: number;
	health: number;
	max_health: number;
	inventory_num: number;
	inventory_max_num: number;
	alignment: string;
	motto: string;
	clan: string;
	time_zone: string;
	diary_last: string;
	mf_at: string | null;
	ark_completed_at: string | null;
	distance: number;
	p_town: string;
	town_name: string;
	in_town: boolean;
	news_h: string;
	arena_fight: boolean;
	bricks_cnt: number;
	wood: string;
	godpower: number;
	clan_position: string;
	a_cmd: boolean;
	pets_max: number;
	au: number;
	arena_won: number;
	arena_lost: number;
	inventory_serial: number;
	max_gp: number;
	gold: number;
	gold_we: string;
	monsters_killed: number;
	death_count: number;
	is_arena_available: boolean;
	d_a: boolean;
	s_a: boolean;
	r_a: boolean;
	is_chf_available: boolean;
	chf_pending: string;
	age_str: string;
	accumulator: number;
	quests_completed: number;
	aln: string;
	dir: string;
	m_id: number;
	m_id_n: number;
	monster_d: string;
	monster_name: string;
	monster_progress: number;
	s_progress: number;
	arena_send_after: number;
	d_send_after: number;
	s_send_after: number;
	r_after: number;
	// biome-ignore lint/suspicious/noExplicitAny: <explanation>
	r_t: any;
	chfr_after: number;
	is_arena_disabled: boolean;
	aura_time: string | null;
	aura_name: string | null;
	q2t: string;
	// biome-ignore lint/suspicious/noExplicitAny: <explanation>
	q2: any[];
	c_town: string;
	poi: number[];
	inv_m: string;
	bla: boolean;
	n_b: number;
	n_l: number;
	n_r: number;
	n_a: number;
	invites_left: number;
	ggender: string;
	arena_god_cmd_disabled: boolean;
}
